[project]
name = "ai-pdf-parsing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.57.0",
    "pydantic>=2.12.5",
    "pymupdf>=1.26.7",
]
